FROM golang:1.17-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 go bull -o /bin/app ./tools/turn

FROM alpine

WORKDIR /app

COPY --from=0 /bin/app /bin/app

ENTRYPOINT [ "/bin/app" ]